### ISSUE TITLE
No longer formatting

### ISSUE THREAD

**Issue by robertbaker** [elad/phoneformat#5]
I agree with you about using make to update. So I'm using your bower package :).

However, the update broke formatting.

phoneformat.min.js:376 Uncaught TypeError: goog.proto2.Message.set$Metadata is not a function

**Comment by christianclent** [comment]
Also getting the same error. Reverted to 0.0.5 for now.

**Comment by robertbaker** [comment]
I tried the latest albeebe/phoneformat.min.js and it works fine.

Probably need to update the code in the closure.js

**Comment by elad** [comment]
Google Code moved to GitHub. After updating references in the relevant places and regenerating it seems to work fine. Give it a try. :)

**Comment by robertbaker** [comment]
Working
